name: Android Build
run-name: ${{ github.event.inputs.build_name }}

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: Build Name
        required: true
        default: Android Build

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - uses: actions/cache@v4
        with:
          path: |
            ~/haxelib
            ~/.haxelib
          key: haxelib-${{ runner.os }}-${{ hashFiles('Project.xml') }}
          restore-keys: haxelib-${{ runner.os }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.hxcpp_cache
            export/release/android/obj
          key: hxcpp-${{ runner.os }}-${{ hashFiles('**/*.hx','Project.xml') }}
          restore-keys: hxcpp-${{ runner.os }}

      - uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang openjdk-17-jdk wget unzip

          haxelib setup ~/haxelib
          haxelib install hxcpp 4.3.2 --quiet

          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Install Android SDK + NDK
        run: |
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip

          mkdir cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true

          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;21.4.7075529"

          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Setup lime + Extra libraries
        run: |
          printf "%s\n%s\n%s\n" \
            "$ANDROID_HOME" \
            "$ANDROID_NDK_ROOT" \
            "$JAVA_HOME" \
            | haxelib run lime setup android

          haxelib git extension-androidtools https://github.com/LimeExtensions/extension-androidtools.git --quiet --skip-dependencies

          haxelib remove linc_luajit || true
          haxelib git linc_luajit https://github.com/ChanceXML/linc_luajit --quiet
          
          haxelib install hxcpp-gh-release --quiet --skip-dependencies
          haxelib dev hxcpp $(haxelib libpath hxcpp-gh-release)       

      - name: Build
        run: |
          echo "${{ github.run_id }}" > VERSION
          haxelib run lime clean android
          haxelib run lime build android -D officialBuild -D LUA_ALLOWED
          find . -name "*.apk"

      - uses: actions/upload-artifact@v4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug/PsychEngine-debug.apk
